services:
    Oro\Bundle\MailChimpBundle\Command\MailChimpExportCommand:
        arguments:
            - '@doctrine'
            - '@oro_message_queue.client.message_producer'
        tags:
            - { name: console.command }
