services:
    _defaults:
        public: true

    Oro\Bundle\MailChimpBundle\Controller\MailChimpController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
          - { name: container.service_subscriber }
