services:
    _instanceof:
        Oro\Component\MessageQueue\Client\TopicSubscriberInterface:
            tags:
                - { name: oro_message_queue.client.message_processor }

    oro_mailchimp.async.export_mailchimp_processor:
        class: Oro\Bundle\MailChimpBundle\Async\ExportMailChimpProcessor
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_integration.reverse_sync.processor'
            - '@oro_mailchimp.static_segment_manager.state_manager'
            - '@oro_message_queue.job.runner'
            - '@security.token_storage'
            - '@logger'
