oro_message_queue:
    time_before_stale:
        jobs:
            'oro_mailchimp:export_mailchimp': 3600

oro_translation:
    package_names:
        # The oro/mailchimp package was a part of oro/crm package initially, and the translations
        # have not been separated into a separate translation package after the split:
        - OroCRM

doctrine:
    orm:
        dql:
            string_functions:
                json_build_object: Oro\Bundle\MailChimpBundle\ORM\Query\AST\Functions\JsonBuildObject
