placeholders:
    placeholders:
        marketing_list_nav_buttons:
            items:
                oro_marketing_list_mailchimp_buttons: ~
        view_navButtons_before:
            items:
                oro_mailchimp_email_campaign_buttons: ~
        view_content_data_email_campaign_status:
            items:
                oro_mailchimp_emailcampaign_stats: ~
        marketing_list_sync_info:
            items:
                oro_mailchimp_marketing_list_sync_data: ~

    items:
        oro_marketing_list_mailchimp_buttons:
            action: Oro\Bundle\MailChimpBundle\Controller\MailChimpController::connectionButtonsAction
            applicable: "@oro_mailchimp.placeholder.filter.buttons_filter->isApplicable($entity$)"
        oro_mailchimp_email_campaign_buttons:
            action: Oro\Bundle\MailChimpBundle\Controller\MailChimpController::emailCampaignActivityUpdateButtonsAction
            applicable: "@oro_mailchimp.placeholder.filter.email_campaign->isApplicableOnEmailCampaign($entity$)"
        oro_mailchimp_emailcampaign_stats:
            action: Oro\Bundle\MailChimpBundle\Controller\MailChimpController::emailCampaignStatsAction
            applicable: "@oro_mailchimp.placeholder.filter.email_campaign->isApplicableOnEmailCampaign($entity$)"
        oro_mailchimp_marketing_list_sync_data:
            action: Oro\Bundle\MailChimpBundle\Controller\MailChimpController::marketingListSyncStatusAction
            applicable: "@oro_mailchimp.placeholder.filter.sync_status->isApplicableOnMarketingList($marketingList$)"
